package com.example.domain.models

data class OrdersResponse(
    val id: Int? = null,
    val parentId: Int? = null,
    val status: String? = null,
    val currency: String? = null,
    val pricesIncludeTax: Boolean? = null,
    val dateCreated: String? = null,
    val dateModified: String? = null,
    val discountTotal: String? = null,
    val discountTax: String? = null,
    val shippingTotal: String? = null,
    val shippingTax: String? = null,
    val cartTax: String? = null,
    val total: String? = null,
    val totalTax: String? = null,
    val customerId: Int? = null,
    val orderKey: String? = null,
    val billing: Billing? = null,
    val shipping: Shipping? = null,
    val paymentMethod: String? = null,
    val paymentMethodTitle: String? = null,
    val transactionId: String? = null,
    val customerIpAddress: String? = null,
    val customerNote: String? = null,
    val dateCompleted: String? = null,
    val datePaid: String? = null,
    val cartHash: String? = null,
    val number: String? = null,
    val lineItems: List<LineItem>? = null,
    val taxLines: List<TaxLine>? = null,
    val shippingLines: List<ShippingLine>? = null,
    val paymentUrl: String? = null,
    val dateCreatedGmt: String? = null,
    val dateModifiedGmt: String? = null,
    val dateCompletedGmt: String? = null,
    val datePaidGmt: String? = null,
    val currencySymbol: String? = null
)