package com.example.domain.models

data class ProductsResponse(
    val id: Int? = null,
    val name: String? = null,
    val slug: String? = null,
    val dateCreated: String? = null,
    val type: String? = null,
    val status: String? = null,
    val featured: Boolean? = null,
    val catalogVisibility: String? = null,
    val description: String? = null,
    val shortDescription: String? = null,
    val sku: String? = null,
    val price: String? = null,
    val regularPrice: String? = null,
    val salePrice: String? = null,
    val dateOnSaleFrom: String? = null,
    val dateOnSaleTo: String? = null,
    val onSale: Boolean? = null,
    val purchasable: Boolean? = null,
    val totalSales: Int? = null,
    val taxStatus: String? = null,
    val taxClass: String? = null,
    val manageStock: Boolean? = null,
    val stockQuantity: Int? = null,
    val soldIndividually: Boolean? = null,
    val shippingRequired: Boolean? = null,
    val shippingTaxable: Boolean? = null,
    val shippingClass: String? = null,
    val shippingClassId: Int? = null,
    val reviewsAllowed: Boolean? = null,
    val averageRating: String? = null,
    val ratingCount: Int? = null,
    val categories: List<Category>? = null,
    val tags: List<Tag>? = null,
    val images: List<Image>? = null,
    val attributes: List<Attribute>? = null,
    val defaultAttributes: List<DefaultAttribute>? = null,
    val stockStatus: String? = null
)